easy_admin:
    entities:
        # List the entity class name you want to manage
        Language:
            class: App\Entity\Language
        TextKey:
            class: App\Entity\TextKey
        GeoPoint:
            class: App\Entity\GeoPoint
        PressRelease:
            class: App\Entity\PressRelease
        SupporterOrganisation:
            class: App\Entity\SupporterOrganisation
            list:
                fields:
                    - 'name'
                    - { property: 'image', type: 'image', base_path: '%app.path.supporter_images%' }
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.supporter_images%' }
            form:
                fields:
                    - 'name'
                    - 'url'
                    - { property: 'imageFile', type: 'vich_image' }
        SupporterPerson:
            class: App\Entity\SupporterPerson
        User:
            class: App\Entity\User
        TranslatedText:
            class: App\Entity\TranslatedText
            form:
                fields:
                    - { property: 'content', type: 'fos_ckeditor' }
                    - 'textKey'
                    - 'language'