vich_uploader:
    db_driver: orm

    mappings:
        supporter_images:
            uri_prefix: /uploads/images/supporters
            upload_destination: '%kernel.project_dir%/public/uploads/images/supporters'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
